# Generated by Django 5.2.1 on 2025-05-12 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('played', 'Jogado'), ('playing', 'Jogando'), ('wishlist', 'Wishlist')], max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
